# Quiz data for Capital Cities Quiz
# Data sourced from country_capitals.xlsx
# Each entry: [country, capital, fun fact]
# Wrong answers are generated randomly at runtime from the full capitals pool

quiz_data = [
    ["Afghanistan", "Kabul",
     "Afghanistan is one of the world's most landlocked countries, surrounded by six different nations!"],
    ["Albania", "Tirana",
     "Albania has more bunkers per square kilometre than any other country — over 170,000 were built during communist rule!"],
    ["Algeria", "Algiers",
     "Algeria is the largest country in Africa by land area, covering about 2.38 million square kilometres!"],
    ["Andorra", "Andorra la Vella",
     "Andorra la Vella is the highest capital city in Europe, sitting at 1,023 metres above sea level!"],
    ["Angola", "Luanda",
     "Angola produces more than 1.7 million barrels of oil per day, making it one of Africa's top oil producers!"],
    ["Argentina", "Buenos Aires",
     "Argentina is the eighth-largest country in the world and the birthplace of the tango dance!"],
    ["Armenia", "Yerevan",
     "Yerevan is one of the world's oldest continuously inhabited cities, with settlements dating back to 782 BC!"],
    ["Australia", "Canberra",
     "Canberra was purpose-built as Australia's capital after Melbourne and Sydney could not agree on which city should hold the title!"],
    ["Austria", "Vienna",
     "Vienna has been ranked as the world's most liveable city multiple times and is famous for its classical music heritage!"],
    ["Bahamas", "Nassau",
     "The Bahamas is made up of over 700 islands and cays, though only about 30 of them are inhabited!"],
    ["Bangladesh", "Dhaka",
     "Dhaka is one of the most densely populated cities on Earth, home to over 21 million people!"],
    ["Belgium", "Brussels",
     "Brussels is home to the headquarters of both NATO and the European Union, making it a global political hub!"],
    ["Bolivia", "Sucre / La Paz",
     "Bolivia is the only country in the world with two capital cities — Sucre (constitutional) and La Paz (administrative)!"],
    ["Brazil", "Brasilia",
     "Brasilia was purpose-built and became Brazil's capital in 1960, replacing Rio de Janeiro!"],
    ["Cambodia", "Phnom Penh",
     "Phnom Penh sits at the meeting point of three major rivers and is known as the Pearl of Asia!"],
    ["Canada", "Ottawa",
     "Canada has the longest coastline of any country in the world, stretching over 202,000 kilometres!"],
    ["Chile", "Santiago",
     "Chile is the longest country in the world from north to south, stretching over 4,300 kilometres!"],
    ["China", "Beijing",
     "China is home to the Great Wall, stretching over 21,000 kilometres — one of the greatest architectural feats in history!"],
    ["Colombia", "Bogota",
     "Colombia is the only country in South America that has coastlines on both the Pacific Ocean and the Caribbean Sea!"],
    ["Costa Rica", "San Jose",
     "Costa Rica has no standing army — it abolished its military in 1948 and redirected the budget to education and healthcare!"],
    ["Croatia", "Zagreb",
     "Croatia has over 1,200 islands along its Adriatic coastline, though fewer than 50 are permanently inhabited!"],
    ["Cuba", "Havana",
     "Cuba has one of the highest literacy rates in the world at over 99%, thanks to a major literacy campaign in 1961!"],
    ["Czech Republic", "Prague",
     "Prague Castle is the largest ancient castle complex in the world, covering over 70,000 square metres!"],
    ["Denmark", "Copenhagen",
     "Denmark is consistently ranked as one of the happiest countries in the world in the annual World Happiness Report!"],
    ["Ecuador", "Quito",
     "Quito is the second-highest capital city in the world, sitting at 2,850 metres above sea level!"],
    ["Egypt", "Cairo",
     "Egypt is home to the Great Pyramid of Giza — the only surviving Wonder of the Ancient World, built over 4,500 years ago!"],
    ["Ethiopia", "Addis Ababa",
     "Addis Ababa is the headquarters of the African Union and serves as a major diplomatic hub for the entire continent!"],
    ["Fiji", "Suva",
     "Fiji is made up of over 330 islands, of which about 110 are permanently inhabited!"],
    ["Finland", "Helsinki",
     "Finland has the most lakes of any country relative to its size — over 188,000 lakes dot the landscape!"],
    ["France", "Paris",
     "France is the most visited country in the world, attracting over 90 million tourists every year!"],
    ["Georgia", "Tbilisi",
     "Georgia is believed to be one of the oldest wine-producing regions in the world, with a winemaking tradition over 8,000 years old!"],
    ["Germany", "Berlin",
     "Germany invented the automobile — Karl Benz patented the first true petrol-powered car in 1886!"],
    ["Ghana", "Accra",
     "Ghana was the first sub-Saharan African country to gain independence from colonial rule, in 1957!"],
    ["Greece", "Athens",
     "Athens is widely regarded as the birthplace of democracy, philosophy, and the Olympic Games!"],
    ["Guatemala", "Guatemala City",
     "Guatemala is home to the ancient Mayan civilisation and has more Mayan ruins than any other country!"],
    ["Haiti", "Port-au-Prince",
     "Haiti was the first Black-led republic in the world and the first Caribbean nation to gain independence, in 1804!"],
    ["Honduras", "Tegucigalpa",
     "Tegucigalpa is one of the few capital cities in the world that is not connected to its country's main highway network!"],
    ["Hungary", "Budapest",
     "Budapest was formed in 1873 by merging three cities — Buda, Obuda and Pest — across the banks of the Danube!"],
    ["Iceland", "Reykjavik",
     "Reykjavik is the world's northernmost capital city and runs almost entirely on geothermal and renewable energy!"],
    ["India", "New Delhi",
     "India invented the number zero! The concept was developed by mathematician Brahmagupta around 628 AD!"],
    ["Indonesia", "Jakarta",
     "Indonesia is the world's largest archipelago nation, made up of over 17,000 islands!"],
    ["Iran", "Tehran",
     "Iran is home to one of the world's oldest continuous civilisations, with recorded history stretching back over 5,000 years!"],
    ["Iraq", "Baghdad",
     "Baghdad was once the largest city in the world and a global centre of learning during the Islamic Golden Age!"],
    ["Ireland", "Dublin",
     "Ireland is known as the Emerald Isle due to its lush green landscape, shaped by its famously rainy climate!"],
    ["Israel", "Jerusalem",
     "Jerusalem is considered a holy city by three major world religions — Judaism, Christianity and Islam!"],
    ["Italy", "Rome",
     "Italy has more UNESCO World Heritage Sites than any other country in the world, with over 58 recognised locations!"],
    ["Jamaica", "Kingston",
     "Jamaica is the birthplace of reggae music and the home of legendary musician Bob Marley!"],
    ["Japan", "Tokyo",
     "Japan has the world's oldest continuous monarchy, dating back over 2,600 years!"],
    ["Kenya", "Nairobi",
     "Nairobi is the only capital city in the world with a national park within its boundaries!"],
    ["Kosovo", "Pristina",
     "Kosovo declared independence in 2008 and is one of the newest countries in the world!"],
    ["Kuwait", "Kuwait City",
     "Kuwait City sits on one of the world's largest oil reserves and has one of the highest GDPs per capita globally!"],
    ["Kyrgyzstan", "Bishkek",
     "Kyrgyzstan is a landlocked country in Central Asia and is home to some of the world's most dramatic mountain scenery!"],
    ["Laos", "Vientiane",
     "Laos is the most heavily bombed country per capita in history, after the Vietnam War era bombings!"],
    ["Latvia", "Riga",
     "Riga's old town is a UNESCO World Heritage Site and is one of the best-preserved medieval city centres in Europe!"],
    ["Lebanon", "Beirut",
     "Beirut is known as the Paris of the Middle East and was once one of the region's most cosmopolitan cities!"],
    ["Lesotho", "Maseru",
     "Lesotho is one of only three countries in the world entirely surrounded by another single country — South Africa!"],
    ["Liberia", "Monrovia",
     "Monrovia is the only capital city in the world named after a US President — James Monroe!"],
    ["Libya", "Tripoli",
     "Libya holds the record for the highest temperature ever reliably recorded on Earth — 57.8°C in 1922!"],
    ["Liechtenstein", "Vaduz",
     "Liechtenstein is one of only two doubly landlocked countries in the world, surrounded entirely by landlocked countries!"],
    ["Lithuania", "Vilnius",
     "Vilnius has one of the largest surviving medieval old towns in Northern Europe, a UNESCO World Heritage Site!"],
    ["Luxembourg", "Luxembourg",
     "Luxembourg is the wealthiest country in the world by GDP per capita and home to major European institutions!"],
    ["Madagascar", "Antananarivo",
     "Madagascar is sometimes called the eighth continent due to its extraordinary biodiversity — 90% of its wildlife is found nowhere else!"],
    ["Malawi", "Lilongwe",
     "Lake Malawi contains more species of fish than any other lake on Earth, with over 1,000 species recorded!"],
    ["Malaysia", "Kuala Lumpur",
     "The Petronas Towers in Kuala Lumpur were the tallest buildings in the world from 1998 to 2004!"],
    ["Maldives", "Male",
     "The Maldives is the lowest-lying country in the world, with an average ground level of just 1.5 metres above sea level!"],
    ["Mali", "Bamako",
     "Mali was home to the ancient city of Timbuktu, once one of the most important centres of Islamic learning in the world!"],
    ["Malta", "Valletta",
     "Valletta is the smallest capital city in the European Union, covering just 0.8 square kilometres!"],
    ["Marshall Islands", "Majuro",
     "The Marshall Islands was the site of 67 US nuclear weapons tests between 1946 and 1958!"],
    ["Mauritania", "Nouakchott",
     "Nouakchott is one of the largest cities in the Sahara Desert and is largely surrounded by sand dunes!"],
    ["Mauritius", "Port Louis",
     "Mauritius was the only known habitat of the dodo bird, which became extinct in the 17th century!"],
    ["Mexico", "Mexico City",
     "Mexico is the birthplace of chocolate! The ancient Aztecs consumed cacao as a sacred drink long before Europe discovered it!"],
    ["Micronesia", "Palikir",
     "Micronesia is made up of over 600 islands scattered across the western Pacific Ocean!"],
    ["Moldova", "Chisinau",
     "Moldova is one of Europe's least-visited countries but is known for producing some excellent wine!"],
    ["Monaco", "Monaco",
     "Monaco is the second-smallest country in the world and has the highest population density of any nation!"],
    ["Mongolia", "Ulaanbaatar",
     "Ulaanbaatar is the coldest capital city in the world, with average winter temperatures dropping below -30°C!"],
    ["Montenegro", "Podgorica",
     "Montenegro's name literally means Black Mountain, named after the dark appearance of Mount Lovcen!"],
    ["Morocco", "Rabat",
     "Morocco is the only African country with coastlines on both the Atlantic Ocean and the Mediterranean Sea!"],
    ["Mozambique", "Maputo",
     "Mozambique has one of the longest coastlines in Africa, stretching over 2,400 kilometres along the Indian Ocean!"],
    ["Myanmar", "Naypyidaw",
     "Naypyidaw was purpose-built as Myanmar's capital in 2005 and is one of the world's largest capital cities by area!"],
    ["Namibia", "Windhoek",
     "Namibia is the least densely populated country in Africa and home to the oldest desert in the world — the Namib!"],
    ["Nauru", "Yaren",
     "Nauru is the smallest island nation in the world and the third-smallest country by area overall!"],
    ["Nepal", "Kathmandu",
     "Nepal is home to eight of the world's ten highest mountains, including Mount Everest — the tallest on Earth!"],
    ["Netherlands", "Amsterdam",
     "The Netherlands has more bicycles than people — there are over 23 million bikes for a population of 17 million!"],
    ["New Zealand", "Wellington",
     "Wellington is the southernmost capital city in the world and is known for its vibrant arts and coffee culture!"],
    ["Nicaragua", "Managua",
     "Nicaragua is the largest country in Central America and is known as the Land of Lakes and Volcanoes!"],
    ["Niger", "Niamey",
     "Niger is the largest country in West Africa by land area and home to a significant part of the Sahara Desert!"],
    ["Nigeria", "Abuja",
     "Nigeria is the most populous country in Africa, with over 220 million people and the continent's largest economy!"],
    ["North Macedonia", "Skopje",
     "North Macedonia only adopted its current name in 2019 after a long-running naming dispute with Greece!"],
    ["Norway", "Oslo",
     "Norway invented the cheese slicer and the paperclip — two of the most useful everyday inventions!"],
    ["Oman", "Muscat",
     "Oman has maintained peaceful diplomatic relations with nearly every country in the world for decades!"],
    ["Pakistan", "Islamabad",
     "Islamabad was purpose-built as Pakistan's capital in the 1960s and replaced Karachi as the seat of government!"],
    ["Palau", "Melekeok",
     "Palau established the world's first shark sanctuary in 2009, banning all commercial shark fishing in its waters!"],
    ["Panama", "Panama City",
     "The Panama Canal connects the Atlantic and Pacific Oceans and is one of the greatest engineering achievements in history!"],
    ["Papua New Guinea", "Port Moresby",
     "Papua New Guinea has extraordinary linguistic diversity — over 800 languages are spoken across the country!"],
    ["Paraguay", "Asuncion",
     "Paraguay is one of only two landlocked countries in South America, along with Bolivia!"],
    ["Peru", "Lima",
     "Peru is home to Machu Picchu, one of the New Seven Wonders of the World and a marvel of Inca engineering!"],
    ["Philippines", "Manila",
     "The Philippines is made up of over 7,600 islands and has the longest coastline of any archipelago in the world!"],
    ["Poland", "Warsaw",
     "Warsaw was almost entirely destroyed during World War II but was meticulously rebuilt to its former glory!"],
    ["Portugal", "Lisbon",
     "Lisbon is one of the oldest cities in Europe and was a major hub of the Age of Exploration in the 15th century!"],
    ["Qatar", "Doha",
     "Qatar has the highest GDP per capita in the world and was the host of the 2022 FIFA World Cup!"],
    ["Republic of the Congo", "Brazzaville",
     "Brazzaville and Kinshasa are the two closest capital cities in the world, separated only by the Congo River!"],
    ["Romania", "Bucharest",
     "Bucharest's Palace of the Parliament is the heaviest building in the world and the second-largest by area!"],
    ["Russia", "Moscow",
     "Russia is the largest country in the world by land area, spanning 11 time zones and over 17 million square kilometres!"],
    ["Rwanda", "Kigali",
     "Rwanda is known as the Land of a Thousand Hills and has one of the highest percentages of women in parliament in the world!"],
    ["Saint Kitts and Nevis", "Basseterre",
     "Saint Kitts and Nevis is the smallest sovereign state in the Western Hemisphere by both area and population!"],
    ["Saint Lucia", "Castries",
     "Saint Lucia has produced more Nobel Laureates per capita than any other country in the world!"],
    ["Samoa", "Apia",
     "Samoa was the first country to see the New Year each year, as it lies just west of the International Date Line!"],
    ["San Marino", "San Marino",
     "San Marino claims to be the world's oldest republic, founded in 301 AD, and is entirely surrounded by Italy!"],
    ["Saudi Arabia", "Riyadh",
     "Saudi Arabia is home to Mecca and Medina, the two holiest cities in Islam, visited by millions of pilgrims each year!"],
    ["Senegal", "Dakar",
     "Dakar was the finish line for the famous Dakar Rally, one of the world's most gruelling off-road races!"],
    ["Serbia", "Belgrade",
     "Belgrade is one of the oldest cities in Europe, with a history stretching back over 7,000 years!"],
    ["Seychelles", "Victoria",
     "Victoria is the smallest capital city in the world by population, home to fewer than 30,000 people!"],
    ["Sierra Leone", "Freetown",
     "Freetown was founded in 1792 as a settlement for freed slaves, giving the city its name!"],
    ["Singapore", "Singapore",
     "Singapore is one of only three city-states in the world and has transformed from a fishing village to a global financial hub in just 60 years!"],
    ["Slovakia", "Bratislava",
     "Bratislava is the only capital city in the world that borders two different countries — Austria and Hungary!"],
    ["Slovenia", "Ljubljana",
     "Ljubljana has been car-free in its historic centre since 2008 and is one of Europe's greenest capital cities!"],
    ["Solomon Islands", "Honiara",
     "The Solomon Islands was the site of one of the fiercest naval battles of World War II!"],
    ["Somalia", "Mogadishu",
     "Mogadishu is one of the oldest cities in East Africa, founded around the 10th century as a trading port!"],
    ["South Africa", "Pretoria",
     "South Africa is the only country in the world to have voluntarily dismantled its own nuclear weapons programme!"],
    ["South Korea", "Seoul",
     "South Korea has one of the fastest average internet speeds in the world and leads globally with brands like Samsung!"],
    ["South Sudan", "Juba",
     "South Sudan is the world's newest country, having gained independence from Sudan in 2011!"],
    ["Spain", "Madrid",
     "Spain is the second-largest country in the EU by area and is famous for flamenco dancing and incredible food!"],
    ["Sri Lanka", "Sri Jayawardenepura Kotte",
     "Sri Lanka is the world's largest producer of Ceylon tea and has been exporting it since the 19th century!"],
    ["Sudan", "Khartoum",
     "Khartoum sits at the exact point where the Blue Nile and White Nile rivers meet and merge!"],
    ["Suriname", "Paramaribo",
     "Suriname is the smallest country in South America and the only Dutch-speaking nation on the continent!"],
    ["Sweden", "Stockholm",
     "Stockholm is built across 14 islands and is often called the Venice of the North!"],
    ["Switzerland", "Bern",
     "Switzerland has four official languages — German, French, Italian and Romansh — reflecting its diverse culture!"],
    ["Syria", "Damascus",
     "Damascus is widely considered to be the oldest continuously inhabited capital city in the world!"],
    ["Taiwan", "Taipei",
     "Taiwan produces around 60% of the world's semiconductors and is a global leader in technology manufacturing!"],
    ["Tajikistan", "Dushanbe",
     "Tajikistan is the smallest country in Central Asia but over 90% of its territory is covered by mountains!"],
    ["Tanzania", "Dodoma",
     "Tanzania is home to Mount Kilimanjaro, the highest peak in Africa at 5,895 metres above sea level!"],
    ["Thailand", "Bangkok",
     "Thailand is the world's largest exporter of rice and is known as the Rice Bowl of Asia!"],
    ["Togo", "Lome",
     "Lome is the only capital city in Africa that sits directly on the coast of the Atlantic Ocean!"],
    ["Tonga", "Nukualofa",
     "Tonga is the only monarchy in the Pacific and has never been colonised by a foreign power!"],
    ["Trinidad and Tobago", "Port of Spain",
     "Trinidad and Tobago is the birthplace of the steel pan drum, the only acoustic instrument invented in the 20th century!"],
    ["Tunisia", "Tunis",
     "Tunisia was the birthplace of the Arab Spring in 2010, sparking a wave of political change across the region!"],
    ["Turkey", "Ankara",
     "Turkey is one of the few countries that straddles two continents — Europe and Asia — and is home to the ancient city of Troy!"],
    ["Turkmenistan", "Ashgabat",
     "Ashgabat holds the world record for the highest density of white marble-clad buildings, earning it a Guinness World Record!"],
    ["Tuvalu", "Funafuti",
     "Tuvalu is one of the most at-risk nations in the world from rising sea levels, with a maximum elevation of just 4.5 metres!"],
    ["Uganda", "Kampala",
     "Uganda is home to roughly half of the world's remaining mountain gorilla population!"],
    ["Ukraine", "Kyiv",
     "Kyiv is one of the oldest cities in Eastern Europe, founded in the 5th century AD!"],
    ["United Arab Emirates", "Abu Dhabi",
     "The UAE is home to the Burj Khalifa in Dubai — the tallest building in the world at 828 metres!"],
    ["United Kingdom", "London",
     "The United Kingdom is the birthplace of the Industrial Revolution, modern football, and the World Wide Web!"],
    ["United States", "Washington, D.C.",
     "The United States has the world's largest economy and put the first humans on the Moon in 1969!"],
    ["Uruguay", "Montevideo",
     "Uruguay was the first country in the world to fully legalise marijuana and has one of South America's highest literacy rates!"],
    ["Uzbekistan", "Tashkent",
     "Tashkent is the largest city in Central Asia and was a key stop on the ancient Silk Road trade route!"],
    ["Vanuatu", "Port Vila",
     "Vanuatu is home to some of the world's most active volcanoes and is considered one of the happiest nations on Earth!"],
    ["Vatican City", "Vatican City",
     "Vatican City is the smallest country in the world by both area and population, covering just 0.44 square kilometres!"],
    ["Venezuela", "Caracas",
     "Venezuela is home to Angel Falls, the world's highest uninterrupted waterfall at 979 metres!"],
    ["Vietnam", "Hanoi",
     "Vietnam is the world's largest producer of cashew nuts and the second-largest exporter of coffee!"],
    ["Yemen", "Sana'a",
     "Sana'a's old city is a UNESCO World Heritage Site and is one of the oldest inhabited cities in the world!"],
    ["Zambia", "Lusaka",
     "Zambia is home to Victoria Falls — one of the world's largest and most spectacular waterfalls!"],
    ["Zimbabwe", "Harare",
     "Zimbabwe is home to a large portion of Victoria Falls and once had one of the highest inflation rates ever recorded!"],
    ["Kiribati", "Tarawa",
     "Kiribati is the only country in the world to span all four hemispheres simultaneously!"],
    ["Korea, North", "Pyongyang",
     "Pyongyang is one of the most controlled and isolated capital cities in the world!"],
    ["Lithuania", "Vilnius",
     "Vilnius has a beautifully preserved Baroque old town that is a UNESCO World Heritage Site!"],
    ["Luxembourg", "Luxembourg",
     "Luxembourg is the only Grand Duchy in the world — a country ruled by a Grand Duke or Duchess!"],
    ["Palestine", "East Jerusalem",
     "Palestine is home to some of the world's oldest cities, including Jericho — believed to be the oldest continuously inhabited city on Earth!"],
]