# Quiz data for Capital Cities Quiz
# Each entry has: country, capital, wrong answers and fun fact

quiz_data = [
    ["France", "Paris", ["Lyon", "Marseille", "Nice"],
     "France is the most visited country in the world, attracting over 90 million tourists a year!"],
    ["Japan", "Tokyo", ["Osaka", "Kyoto", "Hiroshima"],
     "Japan has the world's oldest continuous monarchy, dating back over 2,600 years!"],
    ["Australia", "Canberra", ["Sydney", "Melbourne", "Brisbane"],
     "Australia is the only country that is also a continent, home to more unique wildlife than almost anywhere on Earth!"],
    ["Brazil", "Brasilia", ["Sao Paulo", "Rio de Janeiro", "Salvador"],
     "Brazil is home to the Amazon Rainforest, which produces around 20% of the world's oxygen!"],
    ["Germany", "Berlin", ["Munich", "Hamburg", "Cologne"],
     "Germany invented the automobile - Karl Benz patented the first true petrol-powered car in 1886!"],
    ["Canada", "Ottawa", ["Toronto", "Vancouver", "Montreal"],
     "Canada has the longest coastline of any country in the world, stretching over 202,000 kilometres!"],
    ["India", "New Delhi", ["Mumbai", "Kolkata", "Chennai"],
     "India invented the number zero! The concept was developed by mathematician Brahmagupta around 628 AD!"],
    ["China", "Beijing", ["Shanghai", "Guangzhou", "Shenzhen"],
     "China is home to the Great Wall, stretching over 21,000 kilometres - one of the greatest builds in history!"],
    ["Mexico", "Mexico City", ["Guadalajara", "Monterrey", "Puebla"],
     "Mexico is the birthplace of chocolate! The ancient Aztecs consumed cacao as a sacred drink long before Europe discovered it!"],
    ["South Africa", "Pretoria", ["Cape Town", "Johannesburg", "Durban"],
     "South Africa is the only country in the world to have voluntarily dismantled its own nuclear weapons programme!"],
    ["Argentina", "Buenos Aires", ["Cordoba", "Rosario", "Mendoza"],
     "Argentina is the eighth-largest country in the world and is famous for producing some of the finest beef and Malbec wine!"],
    ["Egypt", "Cairo", ["Alexandria", "Giza", "Luxor"],
     "Egypt is home to the Great Pyramid of Giza - the only surviving Wonder of the Ancient World, built over 4,500 years ago!"],
    ["Italy", "Rome", ["Milan", "Naples", "Turin"],
     "Italy has more UNESCO World Heritage Sites than any other country in the world, with over 58 recognised locations!"],
    ["Spain", "Madrid", ["Barcelona", "Seville", "Valencia"],
     "Spain is the second-largest country in the EU by area and is well known for flamenco dancing and amazing food!"],
    ["Russia", "Moscow", ["Saint Petersburg", "Novosibirsk", "Yekaterinburg"],
     "Russia is the largest country in the world by land area, spanning 11 time zones and over 17 million square kilometres!"],
    ["USA", "Washington DC", ["New York", "Los Angeles", "Chicago"],
     "The United States has the world's largest economy and is known for putting the first humans on the Moon in 1969!"],
    ["UK", "London", ["Manchester", "Birmingham", "Leeds"],
     "The United Kingdom is the birthplace of the Industrial Revolution, modern football, and the World Wide Web!"],
    ["South Korea", "Seoul", ["Busan", "Incheon", "Daegu"],
     "South Korea has one of the fastest average internet speeds in the world and leads global technology with brands like Samsung!"],
    ["Turkey", "Ankara", ["Istanbul", "Izmir", "Bursa"],
     "Turkey is one of the few countries that straddles two continents - Europe and Asia - and is home to the ancient city of Troy!"],
    ["Nigeria", "Abuja", ["Lagos", "Kano", "Ibadan"],
     "Nigeria is the most populous country in Africa, with over 220 million people, and has the continent's largest economy!"],
]